In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('MamaMbogaMoment.csv')

In [3]:
data.head ()

,Date,Title,Full Text,Sentiment,Emotion,Region,Account Type,Author,City,Full Name,...,Mentioned Authors,Priority,Professions,Tags,Total Monthly Visitors,Twitter Author ID,Twitter Followers,Twitter Following,Twitter Tweets,Reach (new)
0,2022-07-19 16:47:28.000,RT @HMureithi @Kenyans This is too low for a m...,RT @HMureithi @Kenyans This is too low for a m...,negative,NaN,NaN,individual,mngesa,NaN,mngesa (sir ali),...,"@hmureithi, @kenyans",NaN,NaN,#MamaMbogaMoment,1414667000,1.342399e+08,32,159,462,0
1,2022-07-10 16:21:50.000,RT @kilundeezy A good reminder @OleItumbi pa...,RT @kilundeezy A good reminder @OleItumbi pay ...,neutral,NaN,Nairobi,individual,Olang_Moses,Nairobi,Olang_Moses (MACHIAVELLIAN),...,"@oleitumbi, @williamsruto",NaN,NaN,#MamaMbogaMoment,1414667000,4.083459e+09,21114,15120,157903,7602
2,2022-07-10 14:36:50.000,RT @kilundeezy A good reminder @OleItumbi pa...,RT @kilundeezy A good reminder @OleItumbi pay ...,neutral,NaN,Nairobi,individual,CaesarToreto,Nairobi,CaesarToreto (Czar),...,"@oleitumbi, @williamsruto",NaN,Sales/Marketing/PR (Digital Media Strategist),#MamaMbogaMoment,1414667000,1.357592e+18,10073,1209,32910,4958
3,2022-07-09 15:45:27.000,RT @kilundeezy A good reminder @OleItumbi pa...,RT @kilundeezy A good reminder @OleItumbi pay ...,neutral,NaN,Nairobi,organisational,kirubimuigai,Nairobi,kirubimuigai (Sports IHub),...,"@oleitumbi, @williamsruto",NaN,NaN,#MamaMbogaMoment,1414667000,7.296242e+17,221,34,8326,0
4,2022-07-09 12:34:16.000,RT @kilundeezy A good reminder @OleItumbi pa...,RT @kilundeezy A good reminder @OleItumbi pay ...,neutral,NaN,Rift Valley,individual,125__iconic,Kericho,125__iconic (yusufu),...,"@oleitumbi, @williamsruto",NaN,NaN,#MamaMbogaMoment,1414667000,1.533716e+18,342,183,1705,0

In [5]:
# Extract unique authors as nodes
nodes = data[['Author', 'Twitter Followers', 'Twitter Following']].drop_duplicates()

# Extract edges based on mentions
mentions = data[['Author', 'Mentioned Authors']]
mentions = mentions.dropna()

# Split mentions into individual mentions and create edges
edges = mentions.assign(Mentioned_Authors=mentions['Mentioned Authors'].str.split(',')).explode('Mentioned_Authors')
edges = edges.rename(columns={'Author': 'Source', 'Mentioned_Authors': 'Target'})

# Remove '@' from the mentioned authors
edges['Target'] = edges['Target'].str.strip().str.replace('@', '')

# Save nodes and edges to CSV
nodes.to_csv('nodes.csv', index=False)
edges.to_csv('edges.csv', index=False)